# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd87ceef253c7e65543615a1651540abc6ed977e4a9404f7c191290a37da2db1b202cd3a7c4f85f7de9f6eb226cb954af77d46295b1c3bddda5ae699b521a852

test:
  secret_key_base: 283510aed52a4bdd55e40142bfa58fc7df666539b347bbdac95c5bf7cc21b9074c1f007a4a0336d597d4ed148f571401c9e187dd28ec17b459e79784f14b0ab2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
